// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFileModification():Promise<boolean>;

export function ExportSearchResults(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<string>;

export function GetAllFields():Promise<Array<string>>;

export function GetAllRecords(arg1:string):Promise<Array<main.JSONRecord>>;

export function GetCommonFields():Promise<Array<string>>;

export function GetFileModificationInfo():Promise<{[key: string]: any}>;

export function GetFileStats():Promise<main.FileStats>;

export function GetPageSize():Promise<number>;

export function GetRecordByLineNumber(arg1:number):Promise<main.JSONRecord>;

export function GetRecordRange(arg1:number,arg2:number):Promise<Array<main.JSONRecord>>;

export function GetRecords(arg1:number,arg2:number):Promise<main.PaginatedRecords>;

export function GetSearchHighlights(arg1:main.JSONRecord,arg2:string,arg3:boolean):Promise<Array<main.HighlightMatch>>;

export function GetTotalRecordCount():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function LoadJSONLFile(arg1:string):Promise<main.JSONLFile>;

export function LoadJSONLFromClipboard():Promise<main.JSONLFile>;

export function OpenFile():Promise<string>;

export function ReloadCurrentFile():Promise<main.JSONLFile>;

export function SearchRecords(arg1:main.SearchOptions):Promise<main.SearchResult>;

export function SearchRecordsWithHighlights(arg1:main.SearchOptions):Promise<main.SearchResult>;

export function SetPageSize(arg1:number):Promise<void>;

export function TestClipboardLoading():Promise<string>;

export function TestFileLoading():Promise<string>;

export function TestFileModificationDetection():Promise<string>;

export function TestJSONLParsing(arg1:string):Promise<string>;

export function TestPagination():Promise<string>;

export function TestSearchFunctionality():Promise<string>;
