// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileModification() {
  return window['go']['main']['App']['CheckFileModification']();
}

export function ExportSearchResults(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportSearchResults'](arg1, arg2, arg3);
}

export function GetAllFields() {
  return window['go']['main']['App']['GetAllFields']();
}

export function GetAllRecords(arg1) {
  return window['go']['main']['App']['GetAllRecords'](arg1);
}

export function GetCommonFields() {
  return window['go']['main']['App']['GetCommonFields']();
}

export function GetFileModificationInfo() {
  return window['go']['main']['App']['GetFileModificationInfo']();
}

export function GetFileStats() {
  return window['go']['main']['App']['GetFileStats']();
}

export function GetPageSize() {
  return window['go']['main']['App']['GetPageSize']();
}

export function GetRecordByLineNumber(arg1) {
  return window['go']['main']['App']['GetRecordByLineNumber'](arg1);
}

export function GetRecordRange(arg1, arg2) {
  return window['go']['main']['App']['GetRecordRange'](arg1, arg2);
}

export function GetRecords(arg1, arg2) {
  return window['go']['main']['App']['GetRecords'](arg1, arg2);
}

export function GetSearchHighlights(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSearchHighlights'](arg1, arg2, arg3);
}

export function GetTotalRecordCount() {
  return window['go']['main']['App']['GetTotalRecordCount']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadJSONLFile(arg1) {
  return window['go']['main']['App']['LoadJSONLFile'](arg1);
}

export function LoadJSONLFromClipboard() {
  return window['go']['main']['App']['LoadJSONLFromClipboard']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReloadCurrentFile() {
  return window['go']['main']['App']['ReloadCurrentFile']();
}

export function SearchRecords(arg1) {
  return window['go']['main']['App']['SearchRecords'](arg1);
}

export function SearchRecordsWithHighlights(arg1) {
  return window['go']['main']['App']['SearchRecordsWithHighlights'](arg1);
}

export function SetPageSize(arg1) {
  return window['go']['main']['App']['SetPageSize'](arg1);
}

export function TestClipboardLoading() {
  return window['go']['main']['App']['TestClipboardLoading']();
}

export function TestFileLoading() {
  return window['go']['main']['App']['TestFileLoading']();
}

export function TestFileModificationDetection() {
  return window['go']['main']['App']['TestFileModificationDetection']();
}

export function TestJSONLParsing(arg1) {
  return window['go']['main']['App']['TestJSONLParsing'](arg1);
}

export function TestPagination() {
  return window['go']['main']['App']['TestPagination']();
}

export function TestSearchFunctionality() {
  return window['go']['main']['App']['TestSearchFunctionality']();
}
